### ISSUE TITLE
cli crashes

### ISSUE THREAD

**Issue by luqasz** [rob-smallshire/eseries#1]
When running `eseries` from cli:
```python
Traceback (most recent call last):
  File "/Users/lkostka/.local/share/virtualenvs/es-T3qevpNt/bin/eseries", line 8, in <module>
    sys.exit(main())
  File "/Users/lkostka/.local/share/virtualenvs/es-T3qevpNt/lib/python3.7/site-packages/eseries/cli.py", line 269, in main
    exit_at_end=False)
TypeError: main() got an unexpected keyword argument 'version'
```

Python 3.7.7
docopt 0.6.2
docopt-subcommands 4.0.0
eseries 1.1.1

**Comment by rob-smallshire** [comment]
This is fixed is the latest version.
